### ISSUE TITLE
feat: create users endpoint

### ISSUE THREAD

**Issue by villaleo** [somos831/somos-backend#1]
Create an SQL table for our users and CRUD endpoints. As of now, the only types of users are Admins. A user table should contain the following fields:
- `first_name`: `varchar(25)`
- `last_name`: `varchar(30)`
- `email`: `varchar(30)`
- `pw_salt_hash`: `varchar(255)`

Endpoints should allow for fetching, creating, updating, removing users.

**Comment by garcialuis** [comment]
For now these are the initial endpoints that I'll be adding for users:
Create User: Endpoint for creating a new user account.
`POST /users`
Retrieve User: Endpoint for retrieving user information.
`GET /users/{id}`: Retrieve user details by ID.
Update User: Endpoint for updating user information.
`PUT /users/{id}`: Update user details by ID.
`PATCH /users/{id}`: Partially update user details by ID.
Delete User: Endpoint for deleting a user account.
`DELETE /users/{id}`: Delete user account by ID.
